input {
  file {
    path => "/loader/*.*"
    mode => "read"
  }
}

filter {
  json {
    source => "message"
  }
  prune {
    blacklist_names => [ "message", "appCln", "appBuild", "appBranch", "appVersion" ]
  }
  geoip {
    source => "[requestIPAddress]"
  }
}

output {
  elasticsearch {
    hosts => "elasticsearch:9200"
  }
}