input {
  sqs {
    "queue" => "basilisk-service-ci"
    "threads" => 150
  }
}

filter {
  prune {
    blacklist_names => [ "appCln", "appBuild", "appBranch", "appVersion" ]
  }
}

filter {
  geoip {
    source => "[requestIPAddress]"
  }
}

output {
  elasticsearch {
    hosts => "elasticsearch:9200"
  }
}