input {
  s3 {
    "bucket" => "waf-adminportal"
  }
}

filter {
  json {
    source => "message"
  }
}

filter {
  date {
    match => [ "timestamp", "UNIX_MS" ]
  }
}

filter {
  geoip {
    source => "[httpRequest][clientIp]"
  }
}

filter {
  ruby {
    path => "/etc/logstash/map_headers.rb"
  }
}

filter {
  ruby {
    path => "/etc/logstash/map_cookies.rb"
  }
}

filter {
  useragent {
    source => "[httpRequest][header][user-agent]"
  }
}

filter {
  mutate {
    remove_field => [ "message", "[httpRequest][headers]" ]
  }
}

output {
  elasticsearch {
    hosts => "elasticsearch:9200"
  }
}