version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - cluster.name=dbz-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - 5601:5601
    networks:
      - esnet
    restart: always
  apm-server:
    image: docker.elastic.co/apm/apm-server:6.3.0
    ports:
      - 8200:8200
    networks:
      - esnet
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    restart: always
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.0
    ports:
      - 5004:5004
      - 9600:9600
    networks:
      - esnet
    restart: always

volumes:
  esdata1:
    driver: local

networks:
  esnet:
